name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xyz219186-ctrl/Realking_kernel_sm8250/
          kernel-dir: msm-4.19
          kernel-branch: main
          config: alioth_defconfig
          arch: arm64
          aosp-gcc: true
          ksu-other: true
          ksu-url: https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh
          android-version: 12
          # Pass MIUI build argument
          make-args: "miui"  # 👈 Added this line to trigger MIUI build
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android-msm-crosshatch-4.9-android12/clang-r416183b.tar.gz
          disable-lto: true
          anykernel3: true
